### PR TITLE
Fix warnings due to API changes in iOS 10, Beta 2

### LINKED ISSUE #63: Assigning to 'id<CALayerDelegate> _Nullable' from incompatible type 'FBShimmeringLayer *const __strong'
First, thanks for this Code.  It's great and it really helped me.

Using Xcode 8, iOS 10 beta 2 and I started getting two warnings in FBShimmeringLayer.m

Line 287 and 400.

`287: _maskLayer.delegate = self;`
...
`400: fadeInAnimation.delegate = self;`

WARNING:
`Assigning to 'id<CALayerDelegate> _Nullable' from incompatible type 'FBShimmeringLayer *const __strong'`

Since I'm a SWIFT developer I'm not quite sure how to fix it myself.  I thought I'd post here before trying to fix it incorrectly myself.

### PR DESCRIPTION
**Pull request by natansh**
iOS 10, Beta 2 introduced changes to `CALayerDelegate` and
`CAAnimationDelegate`, both of which are now proper protocols instead of
informal ones.

This can be seen in the [API diffs](https://developer.apple.com/library/prerelease/content/releasenotes/General/iOS10APIDiffs/Objective-C/QuartzCore.html).

This PR fixes the warnings by introducing a macro which compiles to
those two delegate protocols when on the iOS 10 SDK but compiles to
a placeholder protocol when using the iOS 9 SDK or below.

Fixes #63.

### CODE REVIEW

File: FBShimmering/FBShimmeringLayer.m [hunk 1]
```diff
@@ -24,6 +24,16 @@
 UIKIT_EXTERN float UIAnimationDragCoefficient(void); // UIKit private drag coeffient, use judiciously
 #endif
 
+#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 100000
+#define FBShimmeringCALayerDelegate CALayerDelegate
+#define FBShimmeringCAAnimationDelegate CAAnimationDelegate
```
Comment (kastiglione) [inline FBShimmering/FBShimmeringLayer.m]: Do you think these macros be used anywhere else?

File: FBShimmering/FBShimmeringLayer.m [hunk 2]
```diff
@@ -118,7 +128,7 @@ - (void)layoutSublayers
 
 @end
 
-@interface FBShimmeringLayer ()
+@interface FBShimmeringLayer () <FBShimmeringCALayerDelegate, FBShimmeringCAAnimationDelegate>
```
Comment (kastiglione) [inline FBShimmering/FBShimmeringLayer.m]: Instead of the macro, you could inline right here:

```objc
@interface FBShimmeringLayer ()
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 100000
<CALayerDelegate, CAAnimationDelegate>
#endif
```

**Comment by b3ll** [comment]
I like @kastiglione's solution a bit more, seems cleaner :)

**Comment by natansh** [comment]
@b3ll I agree. It's cleaner to do it as @kastiglione suggested since it's needed in just one location.

**Comment by kastiglione** [comment]
@b3ll do you want to merge this?

**Comment by b3ll** [comment]
💯
